CREATE TABLE projects
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug              VARCHAR(150) NOT NULL UNIQUE,
    title             VARCHAR(200) NOT NULL,
    short_description VARCHAR(500) NOT NULL,
    description       TEXT NOT NULL,
    github_url        VARCHAR(500),
    live_url          VARCHAR(500),
    image_url         VARCHAR(500),
    featured          BOOLEAN      NOT NULL DEFAULT FALSE,
    display_order     INTEGER      NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT projects_display_order_non_negative
        CHECK (display_order >= 0)
);